[package]
name = "bittorrent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
native-tls = "0.2"
sha-1 = "0.10.0"
rand = "0.8.5"
gtk = "0.15.1"
chrono = "0.4.19"
log = "0.4.0"
env_logger = "0.8.4"